export const LOAD_STOPS = "LOAD_STOPS";
export const LOAD_STOP_COMPLETE = "LOAD_STOP_COMPLETE";

export const LOAD_ARRIVALS_COMPLETE = "LOAD_ARRIVALS_COMPLETE";
export const LOAD_ARRIVALS = "LOAD_ARRIVALS";

export const LOAD_ARRIVALS_DATA_REQUEST = "LOAD_ARRIVALS_DATA_REQUEST";
export const LOAD_STOP_DATA_REQUEST = "LOAD_STOP_DATA_REQUEST";

export const CHANGE_VIEW_REQUEST = "CHANGE_VIEW_REQUEST";
export const CHANGE_VIEW = "CHANGE_VIEW";
