export const LOAD_STOPS = "LOAD_STOPS";
export const LOAD_STOP_COMPLETE = "LOAD_STOP_COMPLETE";
export const LOAD_ARRIVALS_COMPLETE = "LOAD_ARRIVALS_COMPLETE";
export const LOAD_ARRIVALS = "LOAD_ARRIVALS";
